### ISSUE TITLE
Comments from Hackathon

### ISSUE THREAD

**Issue by tireddy2** [boucadair/draft-dots-telemetry#6]
Address the comments raised in https://datatracker.ietf.org/meeting/106/materials/slides-106-dots-dots-telemetry-related-hackathon-activity-report-00 

1) Terminology for partial request
2) Context of percentile calculation a) period of time (1hour, 1day ... 1 month) b) time granularity (1sec, 1min, 5min ...) 
3) Separate URI path for baseline and attack telemetry sent in the "telemetry" message type.

**Comment by boucadair** [comment]
fixed
